version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      #- APP_KEY=base64:SomeBase64Key=
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

networks:
  laravel_network:
    driver: bridge
